apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-paradox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production11
  source:
    path: helm
    repoURL: https://github.com/sianrachel/devops-paradox.git
    targetRevision: HEAD
    helm:
      values: |
          image: 2.9.17
          tag: latest
        ingress:
          host: devops-paradox.192.168.64.14.xip.io
      version: v3
  destination:
    namespace: production11
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
